
// A list of the 1000 most common English words.
// Source: https://gist.github.com/deekayen/4148741
const commonWords = new Set([
  "a", "about", "all", "also", "and", "as", "at", "be", "because", "but", "by",
  "can", "come", "could", "day", "do", "even", "find", "first", "for", "from",
  "get", "give", "go", "have", "he", "her", "here", "him", "his", "how", "I",
  "if", "in", "into", "it", "its", "just", "know", "like", "look", "make",
  "man", "many", "me", "more", "my", "new", "no", "not", "now", "of", "on",
  "one", "only", "or", "other", "our", "out", "people", "say", "see", "she",
  "so", "some", "take", "tell", "than", "that", "the", "their", "them", "then",
  "there", "these", "they", "thing", "think", "this", "those", "time", "to",
  "two", "up", "use", "very", "want", "way", "we", "well", "what", "when",
  "which", "who", "will", "with", "would", "year", "you", "your", "after",
  "again", "against", "air", "another", "any", "around", "away", "back",
  "ball", "bear", "beautiful", "before", "began", "being", "below", "between",
  "big", "book", "both", "boy", "bring", "brought", "call", "came", "cannot",
  "car", "children", "city", "close", "cold", "country", "cut", "dark", "did",
  "different", "does", "dog", "don't", "door", "down", "draw", "dream", "drive",
  "each", "early", "earth", "eat", "end", "enough", "every", "example", "eye",
  "face", "family", "far", "father", "feel", "feet", "few", "fire", "fish",
  "five", "follow", "food", "form", "found", "four", "friend", "game", "gave",
  "girl", "good", "got", "great", "ground", "group", "grow", "had", "hand",
  "hard", "has", "head", "hear", "heard", "heart", "help", "high", "hold",
  "home", "horse", "hot", "hour", "house", "hundred", "ice", "idea", "important",
  "inside", "job", "keep", "kind", "knew", "land", "large", "last", "later",
  "learn", "leave", "left", "let", "letter", "life", "light", "line", "list",
  "little", "live", "long", "longer", "love", "made", "may", "mean", "men",
  "might", "mile", "miss", "money", "moon", "morning", "mother", "mountain",
  "move", "much", "must", "name", "near", "need", "never", "next", "night",
  "north", "number", "often", "old", "once", "open", "order", "own", "page",
  "paper", "part", "pass", "past", "picture", "piece", "place", "plant", "play",
  "point", "put", "question", "quick", "quickly", "quite", "rain", "ran", "read",
  "real", "really", "red", "right", "river", "road", "rock", "room", "run",
  "said", "same", "sat", "saw", "school", "sea", "second", "seem", "self",
  "sentence", "set", "several", "ship", "short", "should", "show", "side",
  "sing", "sky", "small", "snow", "something", "song", "soon", "sound", "south",
  "space", "spell", "start", "state", "still", "stop", "story", "study", "such",
  "sun", "sure", "system", "table", "talk", "ten", "test", "thank", "thought",
  "three", "through", "together", "told", "too", "took", "top", "toward", "tree",
  "true", "try", "turn", "under", "understand", "until", "upon", "us", "usually",
  "voice", "walk", "want", "warm", "was", "watch", "water", "white", "while",
  "why", "wind", "without", "woman", "word", "work", "world", "write", "wrote",
  "yellow", "yes", "yesterday", "young", "above", "across", "add", "almost",
  "along", "always", "animal", "answer", "anything", "area", "around", "ask",
  "ate", "away", "bad", "because", "been", "begun", "behind", "best", "better",
  "black", "blue", "body", "box", "build", "buy", "carry", "cause", "center",
  "change", "check", "class", "clear", "color", "coming", "common", "complete",
  "contain", "correct", "course", "cover", "cross", "cry", "deep", "direct",
  "done", "dry", "during", "east", "easy", "effect", "eight", "else", "energy",
  "english", "enjoy", "especially", "ever", "everything", "exactly", "explain",
  "fall", "fast", "felt", "field", "final", "fine", "fly", "foot", "force",
  "free", "front", "full", "general", "getting", "given", "glass", "government",
  "green", "grew", "half", "happen", "happy", "having", "he'd", "he'll", "he's",
  "heavy", "hello", "hence", "hit", "human", "I'd", "I'll", "I'm", "I've",
  "ill", "imagine", "inch", "include", "increase", "instead", "interest",
  "is", "island", "it'd", "it'll", "it's", "keep", "key", "language", "laugh",
  "lead", "less", "let's", "level", "listen", "living", "lost", "lot", "low",
  "machine", "main", "major", "map", "mark", "material", "matter", "measure",
  "meet", "member", "memory", "middle", "mind", "minute", "modern", "moment",
  "month", "most", "music", "myself", "natural", "nearly", "necessary",
  "nothing", "notice", "noun", "object", "ocean", "off", "oh", "oil", "old",
  "onto", "operate", "opportunity", "opposite", "outside", "over", "pair",
  "paint", "parent", "park", "particular", "party", "pattern", "pay", "perhaps",
  "person", "phone", "pick", "plain", "plan", "plane", "please", "plural",
  "position", "possible", "power", "press", "pretty", "print", "probably",
  "problem", "process", "produce", "product", "provide", "pull", "purple",
  "purpose", "push", "race", "radio", "raise", "reach", "ready", "record",
  "remember", "report", "rest", "result", "return", "ride", "ring", "rise",
  "round", "rule", "sand", "science", "score", "season", "seat", "send", "sense",
  "sent", "serve", "service", "shape", "she'd", "she'll", "she's", "shine",
  "shop", "shown", "shut", "simple", "since", "six", "size", "sleep", "slow",
  "slowly", "so", "soft", "soil", "solid", "solution", "soon", "special",
  "spend", "spoke", "spot", "spring", "square", "stand", "star", "stay", "step",
  "stick", "stood", "store", "straight", "street", "strong", "student",
  "subject", "subtract", "sudden", "suddenly", "sugar", "summer", "support",
  "surface", "swim", "symbol", "teach", "teacher", "team", "temperature",
  "that's", "the", "their", "there's", "these", "they'd", "they'll", "they're",
  "they've", "third", "this", "those", "though", "thousand", "today", "told",
  "tomorrow", "too", "total", "touch", "town", "trade", "train", "travel",
  "trip", "trouble", "truck", "truly", "twice", "type", "unable", "uncle",
  "unit", "unite", "unless", "unusual", "up", "use", "value", "various", "verb",
  "very", "view", "visit", "wait", "wall", "war", "wasn't", "watch", "we'd",
  "we'll", "we're", "we've", "wear", "weather", "week", "weight", "well", "went",
  "were", "weren't", "west", "what's", "wheel", "where", "where's", "whether",
  "which", "who's", "whole", "whose", "wide", "wife", "wild", "window", "wing",
  "winter", "wish", "within", "wood", "wouldn't", "wrong", "yet", "you'd",
  "you'll", "you're", "you've", "zero", "zoo"
]);

module.exports = { commonWords };
